L8
elbgoods/laravel-trashmail-rule pull request #15
Opened 2020-10-08 07:55 UTC by mstaack

2020-10-08 08:32 UTC, eisfeuer approved these changes

2020-10-08 08:53 UTC, Gummibeer requested changes

2020-10-08 08:53 UTC, Gummibeer commented on composer.json
> +    "illuminate/support": "^6.0 || ^7.0 || ^8.0"
`orchestra/testbench` fehlt noch

2020-10-08 11:18 UTC, mstaack commented on composer.json
> +    "illuminate/support": "^6.0 || ^7.0 || ^8.0"
done

2020-10-08 11:20 UTC, Gummibeer commented on composer.json
> +    "illuminate/support": "^6.0 || ^7.0 || ^8.0"
https://github.com/elbgoods/laravel-trashmail-rule/pull/15/commits/bd97f4132ed8f143fc57ddcf93886eda3e9fb321

2020-10-08 11:20 UTC, Gummibeer approved these changes

2020-10-08 11:55 UTC, merged

2020-10-13 11:52 UTC, Gummibeer commented
https://github.com/elbgoods/laravel-trashmail-rule/releases/tag/v0.8.0